baseURL = 'https://rundschreiben-kodierer.github.io/handbuch/'
languageCode = 'de-CH'
title = 'Rundschreiben Kodierer'

# Language settings
contentDir = "content/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = []

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = []

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = []

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Language configuration
[languages]
 [languages.de]
  languageName = "Deutsch"
  languageCode = "de"
  contentDir = "content/de"
  weight = 1
 [languages.de.params]
  title = "Handbuch Rundschreiben Kodierer"
  description = "Anleitungen und Informationen zur Rundschreiben Kodierer"

 [languages.fr]
  languageName = "Français"
  languageCode = "fr"
  contentDir = "content/fr"
  weight = 2
 [languages.fr.params]
  title = "Manuel Rundschreiben Kodierer"    
  description = "Instructions et informations sur Rundschreiben Kodierer"

[languages.it]
languageName = "Italian"
languageCode = "it"
contentDir = "content/it"
weight = 3
[languages.it.params]
title = "Manuale Rundschreiben Kodierer"
description = "Guida e informazioni su Rundschreiben Kodierer"

# [languages.rm]
# title = "Manual da plattafurma Rundschreiben Kodierer"
# description = ""
# languageName = "Rumantsch"
# languageCode = "rm"
# contentDir = "content/rm"
# weight = 4

# [languages.en]
# languageName = "English"
# languageCode = "en"
# contentDir = "content/en"
# weight = 5
# [languages.en.params]
# title = "Manual Rundschreiben Kodierer"
# description = "Manual and Information about Rundschreiben Kodierer"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"

# Everything below this are Site Params
[params]
offlineSearch = true
offlineSearchSummaryLength = 0
offlineSearchMaxResults = 100   

# The name corresponds to the name of the site, that is the last element of the baseURL. 
# depending on the environment of execution (production => handbuch, or test => handbuch-test)
# This value is intended to be set by the CI.
# This default value fits the default value of baseURL.
baseName = 'handbuch'

# The version number of the docs. It should correspond to the version of Rundschreiben Kodierer but could also be decorrelated. MUSTN'T BE EMPTY!
# and MUST BE INCREASED at each release!
version = "0.2.0"

# Datetime of the build intended to be set by the CI, LEAVE EMPTY HERE!
buildDatetime = ""

# Hash of the last commit (typically HEAD) intended to be set by the CI, LEAVE EMPTY HERE!
gitHash = ""

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_search_disable = true

# Konfiguration für den Diagramm-Generator Mermaid.
[params.mermaid]
enable = true
theme = "base"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.124.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
