name: Generate node files (node_modules and package-lock.json) for a Windows environment

on:
  workflow_dispatch:

env:
  NODE_VERSION: "20.12.1"

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install 7-Zip
        run: choco install 7zip
        shell: pwsh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack (if needed)
        run: corepack enable

      - name: Verify Node and NPM versions
        run: |
          node -v
          npm -v

      - name: Clean install dependencies
        run: npm install

      - name: Verify package-lock.json changes
        run: |
          git diff package-lock.json || echo "No changes detected"

      - name: Attempt to rebuild npm bin links if .bin is missing
        run: |
          if (-Not (Test-Path "node_modules/.bin")) {
            Write-Host ".bin directory missing, attempting to rebuild..."
            npm rebuild
          }

      - name: Check node_modules/.bin after rebuild
        run: |
          if (Test-Path "node_modules/.bin") {
            Write-Host ".bin directory successfully restored"
          } else {
            Write-Error ".bin directory is still missing!"
            exit 1
          }
          
      - name: Create archive of node_modules
        run: 7z a -tzip -p"P@ssw0rd#10" -mx=0 node_modules.zip node_modules

      - name: Upload node_modules archive
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.zip

      - name: Upload package-lock.json
        uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json
